name: build-and-deploy-docs

on:
  push:
    branches:
      - main    # ou master selon ta branche par défaut
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # Ou la version que tu veux

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser pydata-sphinx-theme
          pip install .

      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
