# Workflow name
name: "Build and deploy Github pages"

# Event that must trigger the workflow
on:
  push:         # <- trigger when we call push
    branches:
      - main  # <- but only on main branch

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    # Task to do when launching the workflow
    steps:

      # 1. First get the repository source

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. Sphinx part : install tool and dependencies

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.16"

      - name: "Install Python dependencies"
        run: |
          pip3 install setuptools
          pip3 install pydata-sphinx-theme
          pip3 install sphinx
          pip3 install numpydoc
          pip3 install myst-parser

      - name: "Install landmark library"
        run: |
          pip install -e .

      - name: "Build Sphinx Doc"
        working-directory: .
        run: |
          sphinx-build -M html ./docs _build 

      # 3. Déploiement sur les Github Pages

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _build/html/
